# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FJAqvgN0UD71jhE0nF309HqgM60lHEAl
"""

import streamlit as st
import pandas as pd
import numpy as np
from scipy.sparse.linalg import svds

# Configuración de la página
st.set_page_config(page_title="Recomendador de Películas IA", page_icon="🍿")
st.title("Descubre tu próxima película favorita")
st.write("Califica estas 5 películas clásicas y nuestra Inteligencia Artificial calculará tus gustos matemáticamente para recomendarte joyas ocultas.")

# 1. Cargar Datos (Usamos cache para que no se recargue cada vez que mueves un botón)
@st.cache_data
def cargar_datos():
    # Cargar calificaciones
    df_ratings = pd.read_csv('u.data', sep='\t', names=['user_id', 'item_id', 'rating', 'timestamp'])
    # Cargar catálogo
    columnas_item = ['item_id', 'title'] + ['col_'+str(i) for i in range(22)] # Simplificado
    df_items = pd.read_csv('u.item', sep='|', names=columnas_item, encoding='latin-1', usecols=['item_id', 'title'])
    return df_ratings, df_items

df_ratings, df_items = cargar_datos()

# 2. Interfaz de Usuario: Las 5 Preguntas (Películas muy conocidas para que el usuario pueda opinar)
st.subheader("Paso 1: Cuéntanos tus gustos")
st.write("Usa 1 si la odiaste, 5 si la amaste. Deja en 3 si no la has visto.")

# IDs de películas famosas en el dataset MovieLens:
# 1: Toy Story, 50: Star Wars, 71: Lion King, 174: Raiders of the Lost Ark, 286: English Patient
peli_1 = st.slider("Toy Story (1995)", 1, 5, 3)
peli_2 = st.slider("Star Wars (1977)", 1, 5, 3)
peli_3 = st.slider("The Lion King (1994)", 1, 5, 3)
peli_4 = st.slider("Raiders of the Lost Ark (1981)", 1, 5, 3)
peli_5 = st.slider("The English Patient (1996)", 1, 5, 3)

# 3. Botón de Acción
if st.button("🔮 Generar mis Recomendaciones", type="primary"):
    with st.spinner('Procesando millones de datos con SVD...'):

        # A. Crear un "Nuevo Usuario" (ID temporal 9999) con las respuestas de la web
        nuevos_ratings = pd.DataFrame({
            'user_id': [9999]*5,
            'item_id': [1, 50, 71, 174, 286],
            'rating': [peli_1, peli_2, peli_3, peli_4, peli_5]
        })

        # B. Unir al dataset original y pivotear
        df_completo = pd.concat([df_ratings[['user_id', 'item_id', 'rating']], nuevos_ratings])
        matriz = df_completo.pivot(index='user_id', columns='item_id', values='rating')

        # C. Matemática: Centrado y SVD
        medias = matriz.mean(axis=1)
        matriz_centrada = matriz.sub(medias, axis=0).fillna(0)

        U, sigma, Vt = svds(matriz_centrada.values, k=20)
        predicciones = np.dot(np.dot(U, np.diag(sigma)), Vt) + medias.values.reshape(-1, 1)

        df_pred = pd.DataFrame(predicciones, index=matriz.index, columns=matriz.columns)

        # D. Extraer resultados para nuestro Usuario 9999
        mis_predicciones = df_pred.loc[9999]
        mis_vistas = matriz.loc[9999]

        # Filtrar las 5 que ya calificó
        no_vistas = mis_predicciones[mis_vistas.isna()]
        top_3 = no_vistas.sort_values(ascending=False).head(3)

        # Cruzar con nombres
        st.subheader("🎉 ¡Tus Recomendaciones!")
        for item_id, rating in top_3.items():
            titulo = df_items[df_items['item_id'] == item_id]['title'].values[0]
            st.success(f"**{titulo}** (Afinidad calculada: {rating:.1f}/5.0)")